services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./www:/var/www/html
    networks:
      - frontend
      - backend

  php:
    image: php:7.4-fpm
    container_name: php
    volumes:
      - ./www:/var/www/html
    networks:
      - backend

  mysql:
    image: mysql:5.7
    container_name: mysql
    networks:
      - backend
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    networks:
      - backend

networks:
  frontend:
  backend:

volumes:
  mysql_data:
